identifier = "SoC"
name = "Stars Of Call"
author = "Hoshikaze 2250 DevTeam"
version = "0.1.0"
abstract = "The Hoshikaze 2250 universe ported into NAEV."
description = '''Hoshikaze 2250 is ao universe developped (in French) by a small team of writers and illustrators. As of 2026, it has been developped into novels, short stories, a Table Top Role-Playing Game and several illustrations. It also features a wiki on our website, containing more than 900 articles. There is also a videogame, named Stars of Call, which used NAEV 0.6 several years ago. The goal of this TC is to upgrade SoC to an up-to-date version of NAEV.'''
license = "CC0"
release_status = "development"
tags = [ "Hoshikaze", "TC" ]
image_url = "Logo-Hoshikaze.png"
naev_version = ">= 0.13.0"
priority = 1
total_conversion = true
source = { git = "https://github.com/Mutos/SoC-TC" }
